/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/Pages/SelectRole.jsx"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#abadaf",
        "secondary-fixed-dim": "#48d3f8",
        "primary": "#0053cc",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#779dff",
        "secondary-dim": "#00576a",
        "surface-bright": "#f5f7f9",
        "tertiary-dim": "#744400",
        "outline": "#747779",
        "on-secondary-fixed-variant": "#00586b",
        "on-secondary-fixed": "#003a47",
        "on-tertiary-fixed": "#2b1600",
        "on-primary": "#f1f2ff",
        "on-background": "#2c2f31",
        "secondary": "#006479",
        "inverse-surface": "#0b0f10",
        "surface": "#f5f7f9",
        "error-dim": "#9f0519",
        "on-tertiary": "#fff0e5",
        "on-primary-fixed": "#000000",
        "tertiary-container": "#fd9d1a",
        "on-tertiary-container": "#4c2b00",
        "on-secondary": "#e0f6ff",
        "tertiary-fixed-dim": "#ed9000",
        "tertiary-fixed": "#fd9d1a",
        "inverse-on-surface": "#9a9d9f",
        "primary-fixed": "#779dff",
        "on-error-container": "#570008",
        "surface-container": "#e5e9eb",
        "on-primary-fixed-variant": "#00286a",
        "inverse-primary": "#5b8cff",
        "on-secondary-container": "#004e60",
        "primary-dim": "#0048b3",
        "surface-container-high": "#dfe3e6",
        "surface-container-low": "#eef1f3",
        "primary-fixed-dim": "#608fff",
        "secondary-fixed": "#77dfff",
        "surface-variant": "#d9dde0",
        "on-surface": "#2c2f31",
        "surface-dim": "#d0d5d8",
        "on-surface-variant": "#595c5e",
        "background": "#f5f7f9",
        "on-tertiary-fixed-variant": "#583300",
        "error": "#b31b25",
        "tertiary": "#854f00",
        "surface-container-highest": "#d9dde0",
        "on-primary-container": "#001f56",
        "secondary-container": "#77dfff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px" },
    },
  },
  important: true,
}
